In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('winequality-red.csv')
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [3]:
df.shape

(1599, 12)

In [4]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [11]:
df.duplicated().sum()

240

In [12]:
df['quality'].value_counts()

5    681
6    638
7    199
4     53
8     18
3     10
Name: quality, dtype: int64

In [13]:
df.dtypes

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
dtype: object

In [14]:
x = df.iloc[:,:-1]  # independent features
y = df.iloc[:,-1]   # dependent feature
print(type(x))
print(type(y))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [15]:
print(x.shape)
print(y.shape)

(1599, 11)
(1599,)


In [16]:
x.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  
0      9.4  
1      9.8  
2      9.8  
3      9.8  
4      9.4

In [17]:
y.head()

0    5
1    5
2    5
3    6
4    5
Name: quality, dtype: int64

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.30)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(1119, 11)
(480, 11)
(1119,)
(480,)


#### Applying Decision Tree Classifier

In [20]:
from sklearn.tree import DecisionTreeClassifier

In [28]:
m1 = DecisionTreeClassifier(criterion='gini',max_depth=9)
m1.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=9)

In [29]:
# Accuracy
print('Training Score',m1.score(x_train,y_train))
print('Testing Score',m1.score(x_test,y_test))

Training Score 0.8766756032171582
Testing Score 0.5583333333333333


In [30]:
ypred_m1 = m1.predict(x_test)
print(ypred_m1)

[5 6 5 5 5 6 4 5 5 6 6 6 6 5 7 5 6 5 5 5 6 7 5 5 6 6 6 5 6 6 5 5 6 6 6 5 5
 5 6 6 5 5 7 6 6 6 6 5 5 5 3 6 6 6 7 5 5 5 7 5 5 5 5 5 6 5 5 6 7 4 7 5 5 6
 7 6 5 6 7 5 5 6 6 7 6 6 5 5 6 5 5 6 5 4 5 5 6 6 6 5 6 5 6 5 6 6 5 5 6 6 5
 5 6 5 5 6 6 6 5 6 5 7 6 5 5 6 6 5 6 7 7 5 6 5 5 5 7 6 6 5 5 6 6 6 5 7 5 5
 5 5 6 5 5 5 6 7 6 6 5 7 6 6 6 6 5 7 6 6 6 5 7 6 5 7 6 6 6 6 5 7 5 5 6 5 6
 6 4 5 5 6 7 5 5 5 5 6 6 5 6 5 6 6 6 5 6 5 6 6 5 4 6 7 5 7 5 5 6 5 6 5 6 5
 6 3 5 5 5 5 5 6 6 5 5 5 5 5 6 5 5 7 6 6 6 6 7 5 7 5 4 5 6 6 5 5 5 6 6 7 6
 7 6 5 5 5 6 6 6 5 6 5 6 6 7 5 5 5 6 6 5 6 5 6 6 6 5 6 5 5 5 6 5 5 5 5 7 6
 5 6 6 6 7 6 6 5 5 7 6 6 6 6 5 7 6 6 5 6 6 5 5 6 6 6 5 6 5 6 4 5 5 5 5 5 5
 5 5 6 5 5 6 7 5 6 6 5 6 4 5 6 6 5 5 6 6 5 5 4 5 6 5 5 5 5 6 5 5 5 4 6 5 5
 7 5 5 5 6 6 6 6 5 6 5 5 5 5 7 5 5 5 5 5 6 6 5 5 6 6 5 5 7 5 6 5 8 5 7 5 5
 7 5 5 6 5 7 6 6 6 5 5 6 5 6 6 6 5 5 5 6 5 5 6 5 5 6 6 5 6 6 5 5 7 5 7 5 6
 5 5 6 6 7 5 6 5 6 7 5 6 7 6 5 5 7 5 6 5 5 5 5 5 6 5 6 5 6 7 5 6 6 6 6 5]


In [31]:
from sklearn.metrics import confusion_matrix,classification_report

In [32]:
cm_m1 = confusion_matrix(y_test,ypred_m1)
print(cm_m1)
print(classification_report(y_test,ypred_m1))

[[  0   0   1   1   0   0]
 [  0   3   8   4   0   0]
 [  2   5 135  49   3   0]
 [  0   2  70 103  16   1]
 [  0   0  12  32  27   0]
 [  0   0   2   2   2   0]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.30      0.20      0.24        15
           5       0.59      0.70      0.64       194
           6       0.54      0.54      0.54       192
           7       0.56      0.38      0.45        71
           8       0.00      0.00      0.00         6

    accuracy                           0.56       480
   macro avg       0.33      0.30      0.31       480
weighted avg       0.55      0.56      0.55       480



#### Applying Random Forest Classifier

In [33]:
from sklearn.ensemble import RandomForestClassifier

In [34]:
m2 = RandomForestClassifier(n_estimators=45, criterion='entropy',max_depth=8,min_samples_split=12) 
m2.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', max_depth=8, min_samples_split=12,
                       n_estimators=45)

In [35]:
# Accuracy
print('Training Score',m2.score(x_train,y_train))
print('Testing Score',m2.score(x_test,y_test))

Training Score 0.8185880250223414
Testing Score 0.6


In [36]:
ypred_m2 = m2.predict(x_test)
print(ypred_m2)

[5 6 5 5 5 6 5 5 5 6 7 6 6 5 6 5 6 5 5 5 6 6 6 5 6 5 5 5 6 5 6 6 6 6 5 5 5
 5 6 5 5 5 7 6 5 6 6 6 6 5 5 6 6 6 6 5 5 5 6 6 5 5 5 5 5 6 5 6 7 5 6 5 5 6
 7 6 5 6 6 5 6 6 6 6 6 5 5 6 6 5 5 5 5 5 5 5 5 6 6 5 5 5 6 5 6 6 5 5 6 6 5
 5 5 5 5 6 6 6 5 6 5 7 6 5 6 6 6 6 6 6 6 5 5 5 5 5 6 5 6 5 6 6 6 6 5 7 5 5
 5 5 5 5 5 5 5 7 6 6 5 7 6 5 6 5 5 6 6 5 7 5 6 5 5 7 6 6 6 6 5 6 5 6 6 5 6
 6 6 5 6 6 7 5 5 5 6 6 5 5 6 6 6 5 6 5 6 6 5 6 5 5 7 6 5 6 5 5 6 5 6 5 6 5
 6 5 5 6 5 5 5 5 6 5 5 6 5 5 6 5 5 7 6 7 6 6 6 5 7 5 5 5 6 5 6 5 5 6 6 6 6
 6 6 6 5 5 6 6 6 5 6 5 6 5 7 5 6 5 7 6 5 6 5 6 6 6 5 6 5 5 6 6 6 5 6 5 6 6
 5 6 6 6 6 6 5 5 5 7 6 6 5 6 5 6 5 6 7 6 6 5 5 6 6 5 5 6 7 6 5 5 6 5 5 5 5
 6 5 6 5 5 6 6 5 6 6 5 6 5 5 6 6 6 5 6 5 5 5 5 5 6 5 5 5 5 6 5 5 5 5 5 5 5
 6 5 5 5 6 5 6 6 5 6 5 5 5 5 7 5 5 5 5 5 6 6 5 5 6 5 5 5 6 5 6 5 6 6 6 5 6
 6 6 5 6 6 7 7 6 6 5 5 6 5 6 6 5 5 5 5 6 5 5 5 5 5 7 6 5 6 7 5 5 6 5 6 5 5
 5 5 5 6 6 5 6 6 6 6 5 6 7 6 5 5 6 5 5 5 5 5 5 6 6 5 6 7 6 7 5 6 6 5 7 5]


In [38]:
cm_m2 = confusion_matrix(y_test,ypred_m2)
print(cm_m2)
print(classification_report(y_test,ypred_m2,zero_division=0))

[[  0   0   1   1   0   0]
 [  0   0  12   3   0   0]
 [  0   0 151  42   1   0]
 [  0   0  72 116   4   0]
 [  0   0   6  44  21   0]
 [  0   0   0   3   3   0]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00        15
           5       0.62      0.78      0.69       194
           6       0.56      0.60      0.58       192
           7       0.72      0.30      0.42        71
           8       0.00      0.00      0.00         6

    accuracy                           0.60       480
   macro avg       0.32      0.28      0.28       480
weighted avg       0.58      0.60      0.57       480



#### Applying KNN Classifier

In [39]:
from sklearn.neighbors import KNeighborsClassifier

In [58]:
m3 = KNeighborsClassifier(n_neighbors=91)
m3.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=91)

In [59]:
# Accuracy
print('Training Score',m3.score(x_train,y_train))
print('Testing Score',m3.score(x_test,y_test))

Training Score 0.5460232350312779
Testing Score 0.5


In [60]:
ypred_m3 = m3.predict(x_test)
print(ypred_m3)

[6 6 5 5 5 5 5 5 5 6 6 6 6 5 6 5 6 5 5 5 6 6 5 5 6 6 6 5 6 5 6 6 5 5 6 5 5
 5 6 5 5 5 6 6 6 6 6 5 6 5 5 6 5 6 6 5 6 6 6 6 5 6 5 5 6 5 5 6 6 6 6 5 5 6
 6 6 5 6 5 6 6 5 6 6 6 5 5 5 6 6 5 5 6 5 5 5 5 6 6 6 5 6 6 6 6 6 5 5 6 6 5
 5 5 5 5 6 6 6 5 5 5 5 5 6 6 6 6 5 6 6 5 5 5 6 5 6 6 6 5 5 6 6 6 6 5 5 5 6
 5 5 5 6 5 5 6 5 5 6 5 6 6 5 6 5 5 6 5 6 6 6 6 6 5 6 6 6 6 6 6 6 6 6 5 6 6
 6 6 5 5 6 6 6 5 6 6 6 5 5 6 6 6 6 5 5 6 6 6 5 6 6 6 6 6 6 5 5 6 5 6 5 5 6
 6 5 6 6 5 5 5 5 6 6 5 6 5 5 5 6 5 6 5 6 6 6 6 5 6 5 5 5 5 6 6 5 5 5 6 6 6
 5 6 6 6 6 6 6 6 5 5 6 6 6 6 6 5 5 6 5 5 5 5 6 6 6 5 5 6 6 6 5 5 5 5 6 6 5
 5 5 6 6 6 6 6 5 5 6 6 5 5 5 5 5 6 6 6 5 6 6 6 6 6 6 5 5 6 6 5 5 6 6 5 6 6
 6 5 6 5 5 6 6 5 6 6 5 6 5 5 6 6 6 6 5 5 5 5 5 6 6 5 6 5 6 5 5 6 5 5 5 6 5
 6 6 5 6 6 6 6 5 5 6 6 5 6 5 6 6 6 5 6 6 6 5 5 6 6 5 5 5 6 5 6 5 6 6 6 5 6
 6 6 6 6 6 6 5 5 6 5 5 6 5 6 6 5 6 5 5 5 5 5 5 5 5 5 6 5 6 6 5 6 6 5 5 5 6
 5 6 5 6 6 5 5 6 6 6 5 6 6 6 5 6 6 5 6 5 5 5 5 5 5 5 6 6 6 6 5 6 6 5 5 6]


In [61]:
cm_m3 = confusion_matrix(y_test,ypred_m3)
print(cm_m3)
print(classification_report(y_test,ypred_m3,zero_division=0))

[[  0   0   0   2   0   0]
 [  0   0  12   3   0   0]
 [  0   0 119  75   0   0]
 [  0   0  71 121   0   0]
 [  0   0  17  54   0   0]
 [  0   0   0   6   0   0]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00        15
           5       0.54      0.61      0.58       194
           6       0.46      0.63      0.53       192
           7       0.00      0.00      0.00        71
           8       0.00      0.00      0.00         6

    accuracy                           0.50       480
   macro avg       0.17      0.21      0.19       480
weighted avg       0.41      0.50      0.45       480



#### Applying SVM Classifier

In [62]:
from sklearn.svm import SVC

In [67]:
m5 = SVC(kernel='linear',C=1)
m5.fit(x_train,y_train)

SVC(C=1, kernel='linear')

In [68]:
# Accuracy
print('Training Score',m5.score(x_train,y_train))
print('Testing Score',m5.score(x_test,y_test))

Training Score 0.6014298480786416
Testing Score 0.55


In [69]:
ypred_m5 = m5.predict(x_test)
print(ypred_m5)

[5 6 5 5 5 6 5 5 5 5 6 6 6 5 6 5 6 5 5 5 6 6 6 5 6 5 5 5 6 5 6 6 6 5 6 5 5
 5 6 5 5 5 6 6 5 6 6 6 6 5 5 6 6 6 6 5 6 5 6 6 5 5 5 5 5 5 5 6 6 5 6 5 5 6
 6 6 5 5 6 5 6 5 6 6 6 5 6 6 6 5 5 5 6 5 5 5 5 5 6 5 5 6 6 5 6 6 5 5 6 6 5
 6 5 5 5 6 6 5 5 6 5 5 6 5 6 6 6 6 6 6 6 6 5 5 5 5 6 6 6 5 6 6 6 6 5 6 5 5
 5 5 5 6 5 5 6 6 5 6 5 6 6 5 6 5 5 6 5 5 6 5 6 5 5 6 5 6 6 6 5 6 5 6 5 5 5
 6 6 5 6 6 6 5 5 5 5 6 5 5 6 6 5 5 6 5 6 5 5 6 5 6 6 6 5 6 5 5 6 6 6 5 6 5
 6 6 6 6 5 5 5 5 6 5 5 6 5 5 5 5 5 6 6 6 6 6 6 5 6 5 5 5 6 6 6 5 5 6 6 6 6
 6 6 6 5 5 6 5 6 5 6 5 5 5 6 5 6 5 6 5 5 6 5 6 6 6 5 6 5 6 5 6 6 5 6 5 6 6
 5 6 5 5 6 6 5 5 5 6 6 6 5 6 6 6 5 6 6 6 6 5 5 6 6 5 5 5 6 5 5 5 6 6 5 5 5
 5 5 6 5 5 6 6 5 6 5 5 6 5 5 6 5 6 5 5 5 5 5 5 5 5 5 5 5 5 6 5 5 5 5 6 5 5
 6 6 5 5 6 5 6 6 5 6 5 5 5 6 6 5 5 5 5 5 6 6 5 5 6 5 5 5 6 5 6 5 6 6 6 5 6
 6 5 5 6 6 6 6 6 6 5 5 6 5 6 6 5 5 5 5 6 6 5 5 5 5 6 6 5 6 6 5 5 6 6 6 5 5
 5 5 5 6 6 5 5 5 5 6 5 6 6 6 5 5 6 6 5 6 5 5 5 6 6 5 6 6 6 6 5 6 6 5 6 5]


In [70]:
cm_m5 = confusion_matrix(y_test,ypred_m5)
print(cm_m5)
print(classification_report(y_test,ypred_m5,zero_division=0))

[[  0   0   2   0   0   0]
 [  0   0  11   4   0   0]
 [  0   0 151  43   0   0]
 [  0   0  79 113   0   0]
 [  0   0   8  63   0   0]
 [  0   0   0   6   0   0]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00        15
           5       0.60      0.78      0.68       194
           6       0.49      0.59      0.54       192
           7       0.00      0.00      0.00        71
           8       0.00      0.00      0.00         6

    accuracy                           0.55       480
   macro avg       0.18      0.23      0.20       480
weighted avg       0.44      0.55      0.49       480



In [88]:
m6 = SVC(kernel='rbf',C=10,gamma=10)
m6.fit(x_train,y_train)

SVC(C=10, gamma=10)

In [89]:
print('Training Score',m6.score(x_train,y_train))
print('Testing Score',m6.score(x_test,y_test))
ypred_m6 = m6.predict(x_test)
print(ypred_m6)

Training Score 1.0
Testing Score 0.5166666666666667
[5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 6 5 5 5 5 5 5 5 5 6 6 5 5 5 5 5 5 5 5 5 5
 5 6 5 5 5 5 5 5 5 5 5 5 5 5 5 6 5 5 5 5 5 7 8 5 5 5 5 5 6 5 5 7 5 5 5 5 5
 5 6 5 5 5 5 5 5 5 5 5 5 5 5 6 5 5 5 5 5 5 5 5 5 5 5 6 5 5 5 5 6 5 5 5 5 5
 5 5 5 5 5 5 5 6 5 5 5 5 5 5 5 5 5 5 7 6 5 5 5 5 5 5 5 5 5 5 5 5 5 5 7 5 6
 5 5 6 5 5 5 5 5 6 5 5 5 5 6 6 5 5 5 5 5 5 5 5 5 5 7 6 5 5 5 5 5 5 5 5 5 5
 6 5 5 5 5 5 5 5 6 5 5 5 5 5 5 5 5 5 5 6 6 6 6 5 5 5 5 5 7 5 5 5 5 6 5 6 5
 6 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 7 5 5 6 6 5 5 7 5 5 5 6 5 7 5 5 5 6 5 5
 7 5 5 5 5 5 5 6 5 5 5 6 5 5 5 5 5 5 5 5 5 5 5 6 6 5 6 5 5 5 6 5 5 5 5 5 5
 5 5 6 5 7 5 5 5 5 5 5 5 6 5 5 5 5 7 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 6 5 5 5 5 6 6 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 7 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 6 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 6 5 5 5 7 5 5 5 5 5 5 5 5 6 5 5 5 5 5 5 5 5 5 5 5 5 5 6 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 6 5 5 5 5 5 5 5 5 5 5 5 5

In [90]:
cm_m6 = confusion_matrix(y_test,ypred_m6)
print(cm_m6)
print(classification_report(y_test,ypred_m6,zero_division=0))

[[  0   0   2   0   0   0]
 [  0   0  14   1   0   0]
 [  0   0 189   5   0   0]
 [  0   0 149  43   0   0]
 [  0   0  56   0  15   0]
 [  0   0   5   0   0   1]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00        15
           5       0.46      0.97      0.62       194
           6       0.88      0.22      0.36       192
           7       1.00      0.21      0.35        71
           8       1.00      0.17      0.29         6

    accuracy                           0.52       480
   macro avg       0.56      0.26      0.27       480
weighted avg       0.70      0.52      0.45       480



In [94]:
m7 = SVC(kernel='poly',C=10,degree=4)
m7.fit(x_train,y_train)

SVC(C=10, degree=4, kernel='poly')

In [95]:
print('Training Score',m7.score(x_train,y_train))
print('Testing Score',m7.score(x_test,y_test))
ypred_m7 = m7.predict(x_test)
print(ypred_m7)

Training Score 0.5245755138516532
Testing Score 0.46458333333333335
[6 6 5 6 5 6 6 6 6 6 6 6 6 5 6 6 6 5 5 5 6 6 6 6 6 6 6 5 6 5 6 6 6 6 6 5 5
 6 6 6 5 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 5 6 5 5 6 6 6 6 5 5 6
 6 6 5 6 6 6 6 6 6 6 6 5 6 6 6 6 6 6 6 6 6 5 6 6 6 6 5 6 6 6 6 6 5 6 6 6 6
 5 6 5 6 6 6 6 5 6 5 6 6 6 6 6 6 6 6 6 6 6 6 6 5 6 6 6 6 5 6 6 6 6 5 6 6 6
 6 5 5 6 5 6 6 6 6 6 6 6 6 5 6 5 5 6 5 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 5 6 6
 6 6 6 6 6 6 6 5 6 6 6 5 5 6 6 6 6 6 5 6 6 6 6 6 6 6 6 6 6 6 6 6 5 6 6 6 6
 6 6 6 6 5 5 6 6 6 6 6 6 5 5 5 6 5 6 6 6 6 6 6 6 6 5 5 5 6 6 6 5 5 6 6 6 6
 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 5 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
 5 6 6 6 6 6 6 5 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 5 6 6 6 6 5 6 6 6 6 6
 6 5 6 6 6 6 6 5 6 6 6 6 6 5 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 5 6 5 6 5 6 5
 6 5 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 5 6 6 5 6 6 6 5 6 5 6 6 6 6 6
 6 6 6 6 6 6 6 6 6 5 5 6 6 6 6 5 6 5 5 6 6 5 6 5 6 6 6 6 6 6 5 6 6 6 6 5 6
 5 6 6 6 6 6 6 6 6 6 5 6 6 6 5 6

In [84]:
cm_m7 = confusion_matrix(y_test,ypred_m7)
print(cm_m7)
print(classification_report(y_test,ypred_m7,zero_division=0))

[[  0   0   0   2   0   0]
 [  0   0   0  15   0   0]
 [  0   0  47 147   0   0]
 [  0   0  26 166   0   0]
 [  0   0   3  67   1   0]
 [  0   0   0   6   0   0]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00        15
           5       0.62      0.24      0.35       194
           6       0.41      0.86      0.56       192
           7       1.00      0.01      0.03        71
           8       0.00      0.00      0.00         6

    accuracy                           0.45       480
   macro avg       0.34      0.19      0.16       480
weighted avg       0.56      0.45      0.37       480



#### Applying LogisticRegression Classifier

In [72]:
from sklearn.linear_model import LogisticRegression

In [74]:
m4 = LogisticRegression(solver='liblinear')
m4.fit(x_train,y_train)

LogisticRegression(solver='liblinear')

In [75]:
# Accuracy
print('Training Score',m4.score(x_train,y_train))
print('Testing Score',m4.score(x_test,y_test))

Training Score 0.5978552278820375
Testing Score 0.5291666666666667


In [76]:
ypred_m4 = m4.predict(x_test)
print(ypred_m4)

[5 6 5 5 5 5 5 5 5 5 6 6 6 5 6 5 6 5 5 5 6 7 5 5 6 5 5 5 6 5 6 5 6 5 6 5 5
 5 6 5 5 5 6 6 5 5 6 6 6 5 5 6 6 6 6 5 6 5 6 6 5 5 5 5 5 5 5 6 6 5 6 5 5 6
 6 6 5 5 6 5 7 5 6 6 6 5 6 6 6 5 5 5 5 5 6 5 5 6 6 5 5 6 6 5 6 6 5 5 6 6 5
 6 5 5 5 6 6 5 5 6 5 5 6 5 6 6 6 6 6 6 6 6 6 5 5 5 7 6 5 5 7 6 6 6 5 6 5 5
 5 5 5 6 5 5 6 6 5 6 5 7 6 5 6 5 5 6 5 5 6 6 6 5 5 6 5 6 6 6 5 6 5 7 5 5 5
 6 6 5 6 6 6 5 5 5 5 6 5 5 6 7 5 5 6 5 6 5 5 5 6 6 6 6 5 6 5 5 6 5 6 5 6 5
 6 6 6 6 5 5 5 5 6 5 5 6 5 5 5 5 5 6 6 6 6 6 6 5 6 5 5 5 5 6 6 5 5 6 6 6 6
 6 6 6 5 5 6 6 6 6 6 5 6 6 6 6 5 5 6 5 5 6 5 6 6 6 5 6 5 6 5 6 6 5 6 5 6 6
 5 6 6 6 6 6 5 5 5 6 6 6 5 6 5 6 5 6 6 6 6 5 5 6 6 5 5 5 6 5 5 5 6 6 5 5 5
 5 5 6 5 5 6 6 5 6 6 5 6 5 5 6 5 6 5 6 5 5 5 5 5 6 5 5 5 5 6 5 5 5 5 5 5 5
 6 5 5 6 6 5 6 6 5 6 5 5 5 6 6 5 5 5 6 5 6 6 5 5 6 5 5 5 6 5 6 5 6 6 6 5 6
 6 5 5 6 6 6 7 6 6 5 5 6 5 6 6 5 5 5 5 6 5 5 5 5 5 6 6 5 6 7 5 5 6 6 5 5 5
 5 5 5 6 6 5 5 5 5 6 5 6 6 6 5 5 6 6 5 6 5 5 5 6 6 5 6 6 6 6 5 6 6 5 6 5]


In [77]:
cm_m4 = confusion_matrix(y_test,ypred_m4)
print(cm_m4)
print(classification_report(y_test,ypred_m4,zero_division=0))

[[  0   0   2   0   0   0]
 [  0   0  11   4   0   0]
 [  0   0 146  47   1   0]
 [  0   0  82 106   4   0]
 [  0   0   8  61   2   0]
 [  0   0   0   4   2   0]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00        15
           5       0.59      0.75      0.66       194
           6       0.48      0.55      0.51       192
           7       0.22      0.03      0.05        71
           8       0.00      0.00      0.00         6

    accuracy                           0.53       480
   macro avg       0.21      0.22      0.20       480
weighted avg       0.46      0.53      0.48       480

